# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box_url = "https://cloud-images.ubuntu.com/vagrant/trusty/current/trusty-server-cloudimg-amd64-vagrant-disk1.box"
  config.vm.box = "trusty64"


  config.vm.define "m1" do |m1|
      m1.vm.provision "shell", path: "./deploy-01.sh"
      m1.vm.hostname = "m1"
      m1.vm.network "private_network", ip: "172.20.20.11"
  end


  config.vm.define "m2" do |m2|
      m2.vm.provision "shell", path: "./deploy-01.sh"
      m2.vm.hostname = "m2"
      m2.vm.network "private_network", ip: "172.20.20.12"
  end


  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", "256"]
    vb.customize ["modifyvm", :id, "--cpuexecutioncap", "50"]
  end

end
