# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "ubuntu/xenial64"
  

  config.vm.define "m1" do |m1|
      m1.vm.hostname = "m1"
      m1.vm.network "private_network", ip: "172.20.20.11"
      m1.vm.network "public_network", type: "dhcp", bridge: "en1"
      #m1.vm.provision "file",  source: "~/.aws", destination: ".aws"
      #m1.vm.provision "shell", path: "./deploy-01.sh"
  end


  config.vm.define "m2" do |m2|
      m2.vm.hostname = "m2"
      m2.vm.network "private_network", ip: "172.20.20.12"
      m2.vm.network "public_network", type: "dhcp", bridge: "en1"
      #m1.vm.provision "file",  source: "~/.aws", destination: ".aws"
      #m1.vm.provision "shell", path: "./deploy-01.sh"
  end


  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", "2048"]
    vb.customize ["modifyvm", :id, "--cpus", "2"]
    vb.customize ["modifyvm", :id, "--cpuexecutioncap", "90"]
  end

end

