# -*- mode: ruby -*-
# vi: set ft=ruby :

# check with: ulimit -n 4048

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  #config.vm.box = "ubuntu/bionic64"
  config.vm.box = "bento/centos-8"

  config.vm.define "m1" do |m1|
      #m1.vm.provision "shell", path: "./deploy-01.sh"
      m1.vm.hostname = "m1"
      m1.vm.synced_folder ".", "/vagrant", type: 'virtualbox'
      m1.vm.network "private_network", ip: "192.168.58.10", virtualbox__intnet: "vboxnet2"
  end

  config.vm.define "m2" do |m2|
    #m2.vm.provision "shell", path: "./deploy-01.sh"
    m2.vm.hostname = "m2"
    m2.vm.synced_folder ".", "/vagrant", type: 'virtualbox'
    m2.vm.network "private_network", ip: "192.168.58.20", virtualbox__intnet: "vboxnet2"
  end

  config.vm.define "m3" do |m3|
    #m2.vm.provision "shell", path: "./deploy-01.sh"
    m3.vm.hostname = "m3"
    m3.vm.synced_folder ".", "/vagrant", type: 'virtualbox'
    m3.vm.network "private_network", ip: "192.168.58.30", virtualbox__intnet: "vboxnet2"
  end

  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", "2048"]
    vb.customize ["modifyvm", :id, "--cpus", "2"]
    #vb.customize ["modifyvm", :id, "--cpuexecutioncap", "80"]
  end

end
