# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import service_pb2 as service__pb2


class CollectorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendEvent = channel.unary_unary(
                '/collector.Collector/SendEvent',
                request_serializer=service__pb2.Metric.SerializeToString,
                response_deserializer=service__pb2.Ack.FromString,
                )
        self.SendMetric = channel.unary_unary(
                '/collector.Collector/SendMetric',
                request_serializer=service__pb2.Metric.SerializeToString,
                response_deserializer=service__pb2.Ack.FromString,
                )
        self.SendMetricStream = channel.stream_unary(
                '/collector.Collector/SendMetricStream',
                request_serializer=service__pb2.Metric.SerializeToString,
                response_deserializer=service__pb2.Ack.FromString,
                )


class CollectorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SendEvent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendMetric(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendMetricStream(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CollectorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendEvent': grpc.unary_unary_rpc_method_handler(
                    servicer.SendEvent,
                    request_deserializer=service__pb2.Metric.FromString,
                    response_serializer=service__pb2.Ack.SerializeToString,
            ),
            'SendMetric': grpc.unary_unary_rpc_method_handler(
                    servicer.SendMetric,
                    request_deserializer=service__pb2.Metric.FromString,
                    response_serializer=service__pb2.Ack.SerializeToString,
            ),
            'SendMetricStream': grpc.stream_unary_rpc_method_handler(
                    servicer.SendMetricStream,
                    request_deserializer=service__pb2.Metric.FromString,
                    response_serializer=service__pb2.Ack.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'collector.Collector', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Collector(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SendEvent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/collector.Collector/SendEvent',
            service__pb2.Metric.SerializeToString,
            service__pb2.Ack.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SendMetric(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/collector.Collector/SendMetric',
            service__pb2.Metric.SerializeToString,
            service__pb2.Ack.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SendMetricStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/collector.Collector/SendMetricStream',
            service__pb2.Metric.SerializeToString,
            service__pb2.Ack.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
