version: '3.9'
services:

  vault:
    image: hashicorp/vault
    container_name: vault
    restart: on-failure:10
    ports:
      - "8201:8201"
    environment:
      VAULT_ADDR: 'https://0.0.0.0:8201'
    cap_add:
      - IPC_LOCK

    volumes:
      - ~/vault-volume:/data
      - ./config:/vault/config

    healthcheck:
      retries: 5

    command: vault server -config /vault/config/vault.json
