# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box_url = "https://cloud-images.ubuntu.com/vagrant/trusty/current/trusty-server-cloudimg-amd64-vagrant-disk1.box"
  config.vm.box = "trusty64"


  config.vm.define "m1" do |m1|
      m1.vm.provision "shell", path: "./deploy-server.sh"
      m1.vm.hostname = "m1"
      m1.vm.network "private_network", ip: "172.20.20.11"
      m1.vm.network "forwarded_port", guest: 80, host: 8080
      m1.vm.network "forwarded_port", guest: 1883, host: 1883
  end


  config.vm.define "m2" do |m2|
      m2.vm.provision "shell", path: "./deploy-client.sh"
      m2.vm.hostname = "m2"
      m2.vm.network "private_network", ip: "172.20.20.12"
  end

  config.vm.define "m3" do |m3|
      m3.vm.provision "shell", path: "./deploy-client.sh"
      m3.vm.hostname = "m3"
      m3.vm.network "private_network", ip: "172.20.20.13"
  end



  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", "512"]
    vb.customize ["modifyvm", :id, "--cpus", "1"]
    vb.customize ["modifyvm", :id, "--cpuexecutioncap", "50"]
  end

end
