# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  #config.vm.box = "ubuntu/xenial64"
  #config.vm.box = "debian/jessie64"
  config.vm.box = "ubuntu/bionic64"


  config.vm.define "m1" do |m1|
      m1.vm.hostname = "m1"
      #m1.vm.network "forwarded_port", guest: 5000, host: 35000, protocol: "tcp"
      #m1.vm.network "forwarded_port", guest: 8000, host: 38000, protocol: "tcp"
      m1.vm.network "private_network", type: "dhcp", bridge: "bridge0"
  end


  config.vm.define "m2" do |m2|
      m2.vm.hostname = "m2"
      m2.vm.network "private_network", type: "dhcp", bridge: "bridge0"
  end



  config.vm.provider :virtualbox do |vb|
    #vb.customize ["modifyvm", :id, "--memory", "2048"]
    vb.customize ["modifyvm", :id, "--memory", "4096"]
    vb.customize ["modifyvm", :id, "--cpus", "2"]
    #vb.customize ["modifyvm", :id, "--cpuexecutioncap", "70"]
  end

end
