version: '3.9'

services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - ~/Documents/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=s3cret
      - POSTGRES_USER=user
      - POSTGRES_DB=demo

