apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: vote
  name: vote
  selfLink: /api/v1/namespaces/default/services/vote
spec:
  externalTrafficPolicy: Cluster
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    run: vote
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
