apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-cluster
  labels:
    {{- include "charts.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-monitor
      app.kubernetes.io/instance: redis-monitor
      app.kubernetes.io/name: redis-monitor
  template:
    metadata:
      labels:
        app: redis-monitor
        app.kubernetes.io/instance: redis-monitor
        app.kubernetes.io/name: redis-monitor
    spec:
      serviceAccountName: {{ include "charts.serviceAccountName" . }}
      containers:
      - name: redis
        image: redis:6.2.3-alpine
        command: ["/start-cluster.sh"]
        volumeMounts:
        - mountPath: /start-cluster.sh
          name: redis-startup
          readOnly: true
          subPath: start-cluster
      volumes:
      - name: redis-startup
        configMap:
          defaultMode: 0530
          name: redis-cluster-configfiles
