version: '2'
services:
  producer:
    image: registry.hub.docker.com/ibanez/rabbitmq:0.2
    command: ./mq-write.py 
    environment:
     - DEBUG=1
    ports:
      - "80:80"
    logging:
      driver: awslogs
      options: 
        awslogs-group: tutorial
        awslogs-region: us-east-1
        awslogs-stream-prefix: producer
 