apiVersion: v1
kind: Pod
metadata:
  name: dapi-test-pod
spec:
  containers:
    - name: test-container
      image: k8s.gcr.io/busybox
      command: [ "/bin/sh", "-c", "ls -l /etc/vmwvro2/; cat /etc/vmwvro2/vro-credentials.yml" ]
      envFrom:
      - configMapRef:
          name: special-config
      volumeMounts:
      - name: vmwvro2
        mountPath: "/etc/vmwvro2"
        readOnly: true
  volumes:
  - name: vmwvro2
    secret:
      secretName: vmwvro2secret  
  restartPolicy: Never
