
- hosts: junos
  roles:
  - Juniper.junos 
  connection: local
  remote_user: root
  gather_facts: no
  tasks:
  - name: Checking NETCONF connectivity
    wait_for: host={{ inventory_hostname }} port=830  timeout=5
  - name: load merge a configuration file
    junos_install_config: 
      host={{ inventory_hostname }}
      file=configs/junos-config-add-op-script.conf
      overwrite=false
      logfile=./config.log

    
