# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "ubuntu/xenial64"
  #config.vm.box = "debian/jessie64"   


  config.vm.define "m1" do |m1|
      m1.vm.hostname = "m1"
      m1.vm.network "forwarded_port", guest: 3000, host: 3000, protocol: "tcp"
      m1.vm.network "forwarded_port", guest: 3443, host: 3443, protocol: "tcp"
      #m1.vm.network "private_network", ip: "172.20.20.11"
      #m1.vm.network "public_network", type: "dhcp", bridge: "en1"
      #m1.vm.provision "file",  source: "~/.aws", destination: ".aws"
      #m1.vm.provision "shell", path: "./deploy-01.sh"
  end


  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", "2048"]
    #vb.customize ["modifyvm", :id, "--memory", "4096"]
    vb.customize ["modifyvm", :id, "--cpus", "2"]
    vb.customize ["modifyvm", :id, "--cpuexecutioncap", "70"]
  end

end
