version: '3.4'

services:
  ipfs:
    image: ipfs/kubo:latest
    container_name: ipfs_host
    ports:
      - "4001:4001"
      - "4001:4001/udp"
      - "127.0.0.1:8080:8080"
      - "127.0.0.1:5001:5001"
    volumes:
      - ~/Downloads/ipfs/staging:/export
      - ~/Downloads/ipfs/data:/data/ipfs
    environment:
      IPFS_PROFILE: server

