# -*- mode: ruby -*-
# vi: set ft=ruby :

# check with: ulimit -n 4048

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "centos/7"

  config.vm.define "m1" do |m1|
      #m1.vm.provision "shell", path: "./deploy-01.sh"
      m1.vm.hostname = "m1"
      m1.vm.synced_folder ".", "/vagrant", type: 'virtualbox'
      m1.vm.network "forwarded_port", guest: 8888, host: 8888
      m1.vm.network "private_network", ip: "192.168.58.10", virtualbox__intnet: "vboxnet2"
  end

  dataDisk = './.vagrant/sb-data.vdi'

  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", "1024"]
    vb.customize ["modifyvm", :id, "--cpus", "2"]
    #vb.customize ["modifyvm", :id, "--cpuexecutioncap", "80"]

    unless File.exist?(dataDisk)
     vb.customize ['createhd', '--filename', dataDisk, '--size', '2000']
    end

    #vb.customize ['storagectl', :id, '--name', 'SATA Controller', '--add', 'sata', '--portcount', 4]
    vb.customize ['storageattach', :id,  '--storagectl', 'SATA Controller', '--port', 1, '--device', 0, '--type', 'hdd', '--medium', dataDisk]
  end

end
