version: '3.5'
name: app-rc
services:

  app:
    image: app-rc
    deploy:
      replicas: 6
    networks:
      - default
      - redis-cluster


networks:
  default:
  redis-cluster:
    name: redis-cluster
    external: true
