# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "dummy"

  config.vm.define "m1" do |m1|
      m1.vm.hostname = "m1"
      m1.vm.provision "file",  source: "~/.aws", destination: "~/.aws"
      m1.vm.provision "shell", path: "./deploy-01.sh"
  end


  config.vm.provider :aws do |aws, override|
    aws.access_key_id = ENV['AWS_ACCESS_KEY_ID']
    aws.secret_access_key = ENV['AWS_SECRET_ACCESS_KEY']

    override.ssh.username = "ubuntu"
    override.ssh.private_key_path = "~/.ssh/kumo.pem"

    aws.keypair_name = "kumo"
    aws.ami = "ami-87564feb"
    aws.instance_type = "m4.large" 
    aws.region ="eu-central-1"
    aws.security_groups = ["docker-machine"]

    aws.tags = {
      'Name' => 'kumo-iou',
      'Client' => 'vagrant'
    }

    aws.region_config "eu-central-1" do |region|
        region.spot_instance = true
        region.spot_max_price = "0.02"
    end

  end

end
