apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-flask
  labels:
    app: flask
spec:
  replicas: 7
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: test-flask
        image: docker.io/ibanez/test-flask:0.3.1-a
        resources:
          limits:
            memory: "200Mi"
            cpu: "100m"
        ports:
        - containerPort: 8888

---
apiVersion: v1
kind: Service
metadata:
  name: flask
spec:
  selector:
    app: flask
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8888

---
apiVersion: networking.k8s.io/v1beta1 # for versions before 1.14 use extensions/v1beta1
kind: Ingress
metadata:
  name: test-flask
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - host: test-flask.info
    http:
      paths:
      - path: /(.*)
        backend:
          serviceName: flask
          servicePort: 80
      - path: /v2/*
        backend:
          serviceName: web2
          servicePort: 8080
