# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "markush81/centos7-vbox-guestadditions"


  config.vm.define "m1" do |m1|
      m1.vm.hostname = "m1"
      #m1.vm.synced_folder ".", "/vagrant", type: 'virtualbox'
  end

  #config.vm.define "m2" do |m2|
  #    m2.vm.hostname = "m2"
  #    #m2.vm.synced_folder ".", "/vagrant", type: 'virtualbox'
  #end


  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", "2048"]
    vb.customize ["modifyvm", :id, "--cpus", "2"]
  end

end
